name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | 
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin de login"

    - name: Build Docker Image
      run: |
        docker build -t fersanti2896/docker-graphql:0.0.2 .
        docker build -t fersanti2896/docker-graphql:latest .

    - name: Push Docker Image
      run: |
        docker push fersanti2896/docker-graphql:0.0.2
        docker push fersanti2896/docker-graphql:latest
    # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
